### ISSUE TITLE
Line chart refactor

### ISSUE THREAD

**Issue by minerop5000** [budgetiser/budgetiser#290]
### Current 
![grafik](https://github.com/budgetiser/budgetiser/assets/75438446/79eca818-de43-4c93-9101-a38d4b512da8)

### Todos
- [ ] animation when y scaling changes
- [ ] half size diagram (y heigth)
- [ ] date selection to bottom
- [ ] swipe control in diagram
   - options
     - keep finger on screen -> see mid point
     - maybe overflow on both sides to see a bit of the other months
